### PR TITLE
Track availability

### PR DESCRIPTION
**Pull request by drsounds**
Added track.availability property on the Track object so you can measure availability.

### CODE REVIEW

**Comment by FrontierPsychiatrist** [comment]
Hi!
Thank you, this is a cool addition! I just would like a little cleanup - I think the first commit is not really necessary for this PR.

The constants from libspotify for the availability should be added [here](https://github.com/FrontierPsychiatrist/node-spotify/blob/b7e8692a565809e5daaf0d31c2b81dce12850b1e/src/objects/node/NodeSpotify.cc#L170) instead in {{spotify.js}}.

**Comment by drsounds** [comment]
I was doing this PR because I'm working on an open source spotify client
called "Bungalow" which adds an own App Finder like platform.
http://github.com/drsounds/bungalow

Best regards,
Alexander Forselius (Dr. Sounds)
Musician, and programmer.
http://dr-sounds.com
<http://t.sigopn04.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fdr-sounds.com%2F&si=5411275823644672&pi=a72820f2-0396-41eb-c4b0-225a140c1614>

Github
<http://t.sigopn04.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.github.com%2Fkrikelin&si=5411275823644672&pi=a72820f2-0396-41eb-c4b0-225a140c1614>
Twitter
<http://t.sigopn04.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.twitter.com%2Fdrsounds&si=5411275823644672&pi=a72820f2-0396-41eb-c4b0-225a140c1614>
Spotify
<http://t.sigopn04.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fopen.spotify.com%2Fartist%2F2FOROU2Fdxew72QmueWSUy&si=5411275823644672&pi=a72820f2-0396-41eb-c4b0-225a140c1614>
<http://t.sigopn04.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dpjdujamrcds&si=5411275823644672&pi=a72820f2-0396-41eb-c4b0-225a140c1614>
LinkedIn
<http://t.sigopn04.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1q0Mw-W8r4PxK7fsJrMW3N1zH656dR01f5JhpKW02?t=http%3A%2F%2Fse.linkedin.com%2Fpub%2Falexander-forselius%2F13%2Fb11%2F500%2F&si=5411275823644672&pi=a72820f2-0396-41eb-c4b0-225a140c1614>


2015-01-24 0:14 GMT+01:00 Moritz Schulze <notifications@github.com>:

**Comment by drsounds** [comment]
Now I moved the constants. Clean it up and accept it please

**Comment by FrontierPsychiatrist** [comment]
I will merge it this weekend.

**Comment by FrontierPsychiatrist** [comment]
Merged in d151699fe0ddd003508e1e15d7c02003881f696f.

**Pull request closed without merging**
